// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkQorS0l_6U2HwbpTzbF9Rqq5sm8KjI8',
    appId: '1:377551713094:web:5b977d040f46b7a18eab47',
    messagingSenderId: '377551713094',
    projectId: 'buy-it-736d7',
    authDomain: 'buy-it-736d7.firebaseapp.com',
    storageBucket: 'buy-it-736d7.appspot.com',
    measurementId: 'G-L9QZSW3F9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3HHYnARDin920CN2lc4LNFwve3KjYuk',
    appId: '1:377551713094:android:185182852fcfeef78eab47',
    messagingSenderId: '377551713094',
    projectId: 'buy-it-736d7',
    storageBucket: 'buy-it-736d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqjM5m7_Hm2MA-72DVUiUCz4t5S6Qdgo',
    appId: '1:377551713094:ios:5a7abb143075a5d38eab47',
    messagingSenderId: '377551713094',
    projectId: 'buy-it-736d7',
    storageBucket: 'buy-it-736d7.appspot.com',
    androidClientId: '377551713094-hujjaehom8b7ccg4g0aehm2v6t3esjab.apps.googleusercontent.com',
    iosClientId: '377551713094-g1spv23ms74e4sbkgrbj531iq0dduogc.apps.googleusercontent.com',
    iosBundleId: 'com.example.App',
  );
}
